/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DATE_PROG 0x20000001
#define DATE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define BIN_TIME 1
extern  long * bin_time_1(void *, CLIENT *);
extern  long * bin_time_1_svc(void *, struct svc_req *);
#define STR_TIME 2
extern  char ** str_time_1(long *, CLIENT *);
extern  char ** str_time_1_svc(long *, struct svc_req *);
extern int date_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BIN_TIME 1
extern  long * bin_time_1();
extern  long * bin_time_1_svc();
#define STR_TIME 2
extern  char ** str_time_1();
extern  char ** str_time_1_svc();
extern int date_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATE_H_RPCGEN */
