/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"


void
date_prog_1(char *host)
{
	CLIENT *clnt;
	long  *bintime;
	char * *strtime;


#ifndef	DEBUG
	clnt = clnt_create (host, DATE_PROG, DATE_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	bintime = bin_time_1(NULL, clnt);
	if (bintime == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    printf("host:%s bintime:%ld\n", host, *bintime);
	strtime = str_time_1(bintime, clnt);
	if (strtime == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
    printf("host:%s strtime:%s\n", host, *strtime);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	date_prog_1 (host);
exit (0);
}
